---
driver:
  name: terraform

provisioner:
  name: terraform

verifier:
  name: terraform
  systems:
    - name: basic
      attrs_outputs:
        client_ips_sofia: client_ips_sofia
        server_ips_sofia: server_ips_sofia
        client_ips_varna: client_ips_varna
        server_ips_varna: server_ips_varna
      backend: local

platforms:
  - name: terraform

suites:
  - name: default
