---
driver:
  name: terraform

provisioner:
  name: terraform

verifier:
  name: terraform
  systems:
    - name: basic
      attrs_outputs:
        client_ips_dc1: client_ips_dc1
        server_ips_dc1: server_ips_dc1
        client_ips_dc2: client_ips_dc2
        server_ips_dc2: server_ips_dc2
      backend: local

platforms:
  - name: terraform

suites:
  - name: default
